[tool.poetry]
name = "modl"
version = "0.1.0"
description = "Rasa mdoel"
authors = ["Your Name <you@example.com>"]
license = "GPL"
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.9"
rasa = "^3.3.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
